/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServidoresRouteImport } from './routes/servidores'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServidoresSlugRouteImport } from './routes/servidores.$slug'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'

const ServidoresRoute = ServidoresRouteImport.update({
  id: '/servidores',
  path: '/servidores',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServidoresSlugRoute = ServidoresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServidoresRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/loja': typeof LojaRoute
  '/regras': typeof RegrasRoute
  '/servidores': typeof ServidoresRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/servidores/$slug': typeof ServidoresSlugRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/loja': typeof LojaRoute
  '/regras': typeof RegrasRoute
  '/servidores': typeof ServidoresRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/servidores/$slug': typeof ServidoresSlugRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/loja': typeof LojaRoute
  '/regras': typeof RegrasRoute
  '/servidores': typeof ServidoresRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/servidores/$slug': typeof ServidoresSlugRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/loja'
    | '/regras'
    | '/servidores'
    | '/admin/pedidos'
    | '/servidores/$slug'
    | '/api/public/mp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/loja'
    | '/regras'
    | '/servidores'
    | '/admin/pedidos'
    | '/servidores/$slug'
    | '/api/public/mp-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conta'
    | '/loja'
    | '/regras'
    | '/servidores'
    | '/admin/pedidos'
    | '/servidores/$slug'
    | '/api/public/mp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContaRoute: typeof ContaRoute
  LojaRoute: typeof LojaRoute
  RegrasRoute: typeof RegrasRoute
  ServidoresRoute: typeof ServidoresRouteWithChildren
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servidores': {
      id: '/servidores'
      path: '/servidores'
      fullPath: '/servidores'
      preLoaderRoute: typeof ServidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servidores/$slug': {
      id: '/servidores/$slug'
      path: '/$slug'
      fullPath: '/servidores/$slug'
      preLoaderRoute: typeof ServidoresSlugRouteImport
      parentRoute: typeof ServidoresRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPedidosRoute: typeof AdminPedidosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPedidosRoute: AdminPedidosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServidoresRouteChildren {
  ServidoresSlugRoute: typeof ServidoresSlugRoute
}

const ServidoresRouteChildren: ServidoresRouteChildren = {
  ServidoresSlugRoute: ServidoresSlugRoute,
}

const ServidoresRouteWithChildren = ServidoresRoute._addFileChildren(
  ServidoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContaRoute: ContaRoute,
  LojaRoute: LojaRoute,
  RegrasRoute: RegrasRoute,
  ServidoresRoute: ServidoresRouteWithChildren,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
